name: ci

on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      packages: write
      contents: read
      attestations: write
    env:
      IMAGE_BASE: ghcr.io/${{ github.repository_owner }}/bitcoin-core-docker
    outputs:
      IMAGE: ${{ fromJson(steps.build.outputs.metadata)['image.name'] }}
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Generate version
        run: |
          # Default tag as commit SHA
          VERSION=${GITHUB_SHA::7}
          # Use tag name if it's a tag push
          if [ "$GITHUB_EVENT_NAME" == "push" ] && [ "$GITHUB_REF_TYPE" == "tag" ]; then
            VERSION=${GITHUB_REF_NAME#v}
          fi
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          provenance: mode=max
          tags: "${{ env.IMAGE_BASE }}:${{ env.VERSION }}"
          cache-from: type=registry,ref=${{ env.IMAGE_BASE }}:buildcache
          cache-to: type=registry,ref=${{ env.IMAGE_BASE }}:buildcache,mode=max

      - name: Attest
        uses: actions/attest-build-provenance@v1
        id: attest
        with:
          subject-name: ${{ env.IMAGE_BASE }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true
  test:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 45
    env:
      CONTAINER_NAME: testnet4
    steps:
      - run: |
          docker pull ${{ needs.build.outputs.IMAGE }}
          docker tag ${{ needs.build.outputs.IMAGE }} bitcoin-core-docker
      - uses: actions/checkout@v4
      - run: ./examples/${CONTAINER_NAME}.sh
      - name: Wait for healthy
        run: |
          while ! docker exec -i ${CONTAINER_NAME} /opt/wallet-health.sh; do
            if ! docker ps | grep ${CONTAINER_NAME}; then
              echo "Container stopped?"
              exit 1
            fi
            echo "waiting for ${CONTAINER_NAME} health"
            echo "Last log: $(docker logs -n1 ${CONTAINER_NAME})"
            sleep 15
          done
      - name: Restart container
        run: |
          docker restart ${CONTAINER_NAME}
      - name: Wait for healthy after restart
        run: |
          while ! docker exec -i ${CONTAINER_NAME} /opt/wallet-health.sh; do
            if ! docker ps | grep ${CONTAINER_NAME}; then
              echo "Container stopped?"
              exit 1
            fi
            echo "waiting for ${CONTAINER_NAME} health"
            echo "Last log: $(docker logs -n1 ${CONTAINER_NAME})"
            sleep 15
          done